name: push to protected
on:
  workflow_dispatch:

jobs:
  push:
    name: push to protected
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          date > date.txt
          git add .
          git commit -m "push to protected"
          git push origin
