name: push to protected
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  push:
    name: push to protected
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: push
        env:
          GITHUB_TOKEN: ${{ secrets.KEY }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          date > date.txt
          git add .
          git commit -m "push to protected"
          git push origin main
