name: push to protected
on:
  workflow_dispatch:

jobs:
  push:
    name: push to protected
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          date > date.txt
          git add .
          git commit -m "push to protected"
          git push
