name: push to protected
on:
  workflow_dispatch:

jobs:
  push:
    name: push to protected
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          date > date.txt
          git add .
          git commit -m "push to protected"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
